# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d2b60f1b27bb6703ae87bde788147eb3b28b1580ff7d1ef64736a396ed657eb58519a238bb7c76d5cee3314ab5b20a0ba54961aa5187bd5c939813ed5790ca5

test:
  secret_key_base: bb0679675ede4d00a6c1cb2f7a77c8aa1520afba831d5bd0ddd8f1cd302e5aacc4878674c7ef35fe916d489358c3a677051c52cd5040a64004ea0690af63d23e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
